name: Deploy to server

on: push

jobs:
  first_jobs:
    runs-on: ubuntu-latest

    env:
      NAME: CodigoFacilito
    steps:
      - name: Working dir
        id: step_1
        run: echo "my_variable = Hola mundo" >> $GITHUB_OUTPUT

      - name: Obtener mensaje
        run: echo "${{ steps.step1.outputs.my_variable }}" # Esto imprime el valor de my_variable

  second_job:
    if: ${{ github.ref == 'refs/heads/main' }} # Solo se ejecuta el job si el push es a la rama main
    needs: first_jobs #Nos ayuda a crear dependencias entre jobs
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo
        run: echo "Hola mundo segundo ${{ github.ref }}"        